# Generated by Django 3.2.5 on 2022-01-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phn_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phn_verification_token_created_at',
        ),
    ]
